class OptionDisplayCPModel {
  final String acpr,
      unch_prpr,
      optn_shrn_iscd,
      optn_prpr,
      optn_prdy_vrss,
      prdy_vrss_sign,
      optn_prdy_ctrt,
      optn_bidp,
      optn_askp,
      tmvl_val,
      nmix_sdpr,
      acml_vol,
      seln_rsqn,
      shnu_rsqn,
      acml_tr_pbmn,
      hts_otst_stpl_qty,
      otst_stpl_qty_icdc,
      delta_val,
      gama,
      vega,
      theta,
      rho,
      hts_ints_vltl,
      invl_val,
      esdg,
      dprt,
      hist_vltl,
      hts_thpr,
      optn_oprc,
      optn_hgpr,
      optn_lwpr,
      optn_mxpr,
      optn_llam,
      atm_cls_name,
      rgbf_vrss_icdc,
      total_askp_rsqn,
      total_bidp_rsqn,
      futs_antc_cnpr,
      futs_antc_cntg_vrss,
      antc_cntg_vrss_sign,
      antc_cntg_prdy_ctrt;

  OptionDisplayCPModel.fromjson(Map<String, dynamic> json)
      : acpr = json['acpr'],
        unch_prpr = json['unch_prpr'],
        optn_shrn_iscd = json['optn_shrn_iscd'],
        optn_prpr = json['optn_prpr'],
        optn_prdy_vrss = json['optn_prdy_vrss'],
        prdy_vrss_sign = json['prdy_vrss_sign'],
        optn_prdy_ctrt = json['optn_prdy_ctrt'],
        optn_bidp = json['optn_bidp'],
        optn_askp = json['optn_askp'],
        tmvl_val = json['tmvl_val'],
        nmix_sdpr = json['nmix_sdpr'],
        acml_vol = json['acml_vol'],
        seln_rsqn = json['seln_rsqn'],
        shnu_rsqn = json['shnu_rsqn'],
        acml_tr_pbmn = json['acml_tr_pbmn'],
        hts_otst_stpl_qty = json['hts_otst_stpl_qty'],
        otst_stpl_qty_icdc = json['otst_stpl_qty_icdc'],
        delta_val = json['delta_val'],
        gama = json['gama'],
        vega = json['vega'],
        theta = json['theta'],
        rho = json['rho'],
        hts_ints_vltl = json['hts_ints_vltl'],
        invl_val = json['invl_val'],
        esdg = json['esdg'],
        dprt = json['dprt'],
        hist_vltl = json['hist_vltl'],
        hts_thpr = json['hts_thpr'],
        optn_oprc = json['optn_oprc'],
        optn_hgpr = json['optn_hgpr'],
        optn_lwpr = json['optn_lwpr'],
        optn_mxpr = json['optn_mxpr'],
        optn_llam = json['optn_llam'],
        atm_cls_name = json['atm_cls_name'],
        rgbf_vrss_icdc = json['rgbf_vrss_icdc'],
        total_askp_rsqn = json['total_askp_rsqn'],
        total_bidp_rsqn = json['total_bidp_rsqn'],
        futs_antc_cnpr = json['futs_antc_cnpr'],
        futs_antc_cntg_vrss = json['futs_antc_cntg_vrss'],
        antc_cntg_vrss_sign = json['antc_cntg_vrss_sign'],
        antc_cntg_prdy_ctrt = json['antc_cntg_prdy_ctrt'];
}
