class StockBalanceModel {
  final String pdno,
      prdt_name,
      trad_dvsn_name,
      bfdy_buy_qty,
      thdt_buyqty,
      thdt_sll_qty,
      hldg_qty,
      ord_psbl_qty,
      pchs_avg_pric,
      pchs_amt,
      prpr,
      evlu_amt,
      evlu_pfls_amt,
      evlu_pfls_rt,
      evlu_erng_rt,
      loan_dt,
      loan_amt,
      stln_slng_chgs,
      expd_dt,
      fltt_rt,
      bfdy_cprs_icdc,
      item_mgna_rt_name,
      grta_rt_name,
      sbst_pric,
      stck_loan_unpr;

  StockBalanceModel.fromjson(Map<String, dynamic> json)
      : pdno = json['pdno'],
        prdt_name = json['prdt_name'],
        trad_dvsn_name = json['trad_dvsn_name'],
        bfdy_buy_qty = json['bfdy_buy_qty'],
        thdt_buyqty = json['thdt_buyqty'],
        thdt_sll_qty = json['thdt_sll_qty'],
        hldg_qty = json['hldg_qty'],
        ord_psbl_qty = json['ord_psbl_qty'],
        pchs_avg_pric = json['pchs_avg_pric'],
        pchs_amt = json['pchs_amt'],
        prpr = json['prpr'],
        evlu_amt = json['evlu_amt'],
        evlu_pfls_amt = json['evlu_pfls_amt'],
        evlu_pfls_rt = json['evlu_pfls_rt'],
        evlu_erng_rt = json['evlu_erng_rt'],
        loan_dt = json['loan_dt'],
        loan_amt = json['loan_amt'],
        stln_slng_chgs = json['stln_slng_chgs'],
        expd_dt = json['expd_dt'],
        fltt_rt = json['fltt_rt'],
        bfdy_cprs_icdc = json['bfdy_cprs_icdc'],
        item_mgna_rt_name = json['item_mgna_rt_name'],
        grta_rt_name = json['grta_rt_name'],
        sbst_pric = json['sbst_pric'],
        stck_loan_unpr = json['stck_loan_unpr'];
}
